<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <title>The page you were looking for doesn't exist (404)</title>
        <style type="text/css">
            body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }
            div.dialog {
                width: 25em;
                padding: 0 4em;
                margin: 4em auto 0 auto;
                border: 2px solid #ccc; 
                background-color: #eeeeff;
            }
            h1 { font-size: 100%; color: #f00; line-height: 1.5em; }
        </style>
    </head>

    <body>
        <div class="dialog">
            <h1>404: The page you were looking for doesn't exist.</h1>
        </div>
    </body>
</html>
